### ISSUE TITLE
[ Suggestion ] Auction bar messages.

### ISSUE THREAD

**Issue by Godwhitelight** [gXLg/libr-getter#11]
Change the chat messages to auction messages. so it won't spam the chat so badly.

**Comment by gXLg** [comment]
No, this is intended, so that you can see, what happened in the past

**Comment by gXLg** [comment]
With the new configs available up from 1.2.7, it now makes sense to further work on this issue

**Comment by gXLg** [comment]
done, now just have to port tot all versions and release

**Comment by gXLg** [comment]
Done in [v1.3.0](https://github.com/gXLg/libr-getter/releases/tag/v.1.3.0)
