### ISSUE TITLE
Lag compensation

### ISSUE THREAD

**Issue by SnowSquire** [gXLg/libr-getter#14]
If the server lags while tryng to play the lectern then the mod will not try to place the lectern again

**Comment by gXLg** [comment]
I did not think of this lag, thanks for pointing that out. A fix is already known and will be implemented asap

**Comment by gXLg** [comment]
done, now just have to port tot all versions and release

**Comment by gXLg** [comment]
Done in [v1.3.0](https://github.com/gXLg/libr-getter/releases/tag/v.1.3.0)
