### ISSUE TITLE
Unknow or Incomplete Command

### ISSUE THREAD

**Issue by matsal007** [gXLg/libr-getter#19]
Hey there! Just installed the last version for 1.16.5, and I can use the commands such as /librget add, and options and the other ones, but whenever I tried to 'get' the villager it returns a Unknow or Incomplete Command
![image](https://github.com/gXLg/libr-getter/assets/74623222/d560f9a1-1882-4320-8931-0e213b53f157)

**Comment by gXLg** [comment]
At some point I moved the line and it got lost. Thank you for pointing this out!
I have already found the bug and will fix it as soon as possible. Meanwhile I suggest you to use `/librget auto`, or to manually select villager and lectern `/librget config` should work (this is the isse, the kine of code responsible for this just slipped)

**Comment by gXLg** [comment]
Actually @7coil already found out about it, I just didn't notice the issue, I'm sorry for that. Expect the update to come out on Sunday including 1.20.2

**Comment by matsal007** [comment]
Thx so much, I actually didn't knew that `/librget auto` did what it did and installed a older version, so thank you again.

**Comment by gXLg** [comment]
Meh, the issue is yet not completed :) I will re-open for me to work on this
