### ISSUE TITLE
Modrinth/CurseForge Uploading

### ISSUE THREAD

**Issue by xnousnow** [gXLg/libr-getter#21]
I would like to see this mod on websites, making it easier to find or install.

**Comment by gXLg** [comment]
I have considered this, I will maybe create a page on modrinth. Thank you for the suggestion

**Comment by gXLg** [comment]
I created the page and a workflow to automatically upload the mod. Now we will wait until my project is accepted

**Comment by gXLg** [comment]
The mod is now [Modrinth](https://modrinth.com/mod/libr-getter). I will add a new download description on a new release
