### ISSUE TITLE
Minor bug/issue 

### ISSUE THREAD

**Issue by MilesTFox** [gXLg/libr-getter#24]
When you're running for books from enchantment solution, you can receive just 'book', 
The process will error and stop, and not proceed till you break and replace the lectern once manually to reset the villager.

Using v2.0.1 with mc 1.20.2

![image](https://github.com/gXLg/libr-getter/assets/21246610/077af963-5819-4fae-b0b7-0b2919196e63)
![image](https://github.com/gXLg/libr-getter/assets/21246610/047c85c3-73b7-498c-8323-65277f66bd6d)

**Comment by gXLg** [comment]
Don't know, why villagers need to trade for just books, lol. But yeah, the stopping sucks.
It's actually quite simple, but this `tag==null` check is also kinda required - I will see what I can do

**Comment by gXLg** [comment]
Fixed in [v2.0.2](https://github.com/gXLg/libr-getter/releases/tag/v2.0.2)
