### ISSUE TITLE
villagers not turning when placing lectern too fast

### ISSUE THREAD

**Issue by Nathaniel512** [gXLg/libr-getter#25]
when breaking and placing the lectern too fast, the villager gets confused and stops looking for the lectern. adding a way to add a delay between breaking the lectern may resolve the issue?

**Comment by gXLg** [comment]
I will investigate into the job acquiring mechanism in Minecraft's code and will report back later once I found a good solution

**Comment by Nathaniel512** [comment]
> I will investigate into the job acquiring mechanism in Minecraft's code and will report back later once I found a good solution

nvm, i was being silly and my setup he could see other work stations so thats what messed it up. im sorry, i dont know how to close this or even how to delete it. sorry for the disturbence

**Comment by gXLg** [comment]
It's alright, don't worry.
