### ISSUE TITLE
"/librget list" issue

### ISSUE THREAD

**Issue by Jus7ifier** [gXLg/libr-getter#27]
output of "/librget list" is:
java.lang.NoSuchMethodException: 
net.minecraft.class_2588.<init>()

**Comment by gXLg** [comment]
thanks for pointing this out, which version are you running LibrGetter on?

**Comment by gXLg** [comment]
Also, if any, can you tell, which mods you are using, for me to check the if there are some incompatibilities?

**Comment by Jus7ifier** [comment]
sorry for delay
i'm using ver. 2.0.2 on 1.18.2
my mods list in pinned spreadsheet
[mc-mod-list.xlsx](https://github.com/user-attachments/files/15987484/mc-mod-list.xlsx)

**Comment by gXLg** [comment]
Thanks, I will work on it in the near future

**Comment by gXLg** [comment]
Fixed in [v.2.1.0](https://github.com/gXLg/libr-getter/releases/tag/v2.1.0)
