### ISSUE TITLE
compatibility or just a crash from the mod?

### ISSUE THREAD

**Issue by TwoPointInfinity** [gXLg/libr-getter#3]
https://pastebin.com/Vr9adFv2

**Comment by TwoPointInfinity** [comment]
crash on launch

**Comment by TwoPointInfinity** [comment]
https://pastebin.com/KMRW25hM removed all mods, still crashes. fabric 1.19.2

**Comment by gXLg** [comment]
sorry about that, the mod is actually not available for 1.19.* yet, did not write correct in the descriptio. I will fix this in one-two days and there will be new version available (just wait for it in releases)

**Comment by gXLg** [comment]
Added version 1.19.2 to releases: https://github.com/gXLg/libr-getter/releases/tag/v1.2.3
