### ISSUE TITLE
Slower a bit

### ISSUE THREAD

**Issue by ToanAnh312** [gXLg/libr-getter#30]
i need it 1 tick slower so any pc that has lag issue, the thing is villager lose the job a bit slower while the lectern being placed almost immediately and it confuse the game so the villager cannot get the job

**Comment by gXLg** [comment]
Yes, you are right! I was focused on optimization in my last update and completely forgot about lag. I will add this as a config in the near future

**Comment by ToanAnh312** [comment]
oops wrong button, btw you can also add a "timer" so after 2-5s of villager not responding, replace(or destroying and wait for some tick) lectern. This is suitable for no delay in config

**Comment by gXLg** [comment]
Previously I had it by default, that the mod waits until the villager loses its' profession, before placing the lectern back again. I believe adding this as a toggleable config option would be pretty suitable for this case.
If you are laggy, you can turn this on, and the mod will be less efficient, but work for sure. If your client isn't lagging, you can turn it off and the mod will replace the lectern without waiting and be more efficient

**Comment by ToanAnh312** [comment]
i hope you can add it asap xD

**Comment by gXLg** [comment]
Done in [v2.1.1](https://github.com/gXLg/libr-getter/releases/tag/v2.1.1) 🎉

**Comment by gXLg** [comment]
I will add the timeout function in the next version
