### ISSUE TITLE
Villager interfere ?

### ISSUE THREAD

**Issue by ToanAnh312** [gXLg/libr-getter#31]
In older version, it works well but in recents one, i cant start it although no way it can interfere
Yep, you must place sthing above lectern but sometime you dont need to and it may confuse someone who just use it recently
![image](https://github.com/user-attachments/assets/f5e7a0a7-3617-4069-84c4-fbf8116b98f2)
![image](https://github.com/user-attachments/assets/8da55610-2430-4d06-8560-dc29cb7ac87b)

**Comment by ToanAnh312** [comment]
the older version is the one that don't have lectern delay (as i reported)

**Comment by ToanAnh312** [comment]
Here, the mod no longer work 

https://github.com/user-attachments/assets/ac95a09d-d3cf-4279-bcca-67ea62ef886c

**Comment by ToanAnh312** [comment]
So, because of trapdoor attribute different, the villager still think it can go through, and maybe that is how mod detect. still work if replace/ trap it with blocks, slabs,etc BUT trapdoor, please fix :D

**Comment by gXLg** [comment]
Sorry for that. I'm addressing this issue in the next update.
For now, you might want to turn off the safe checker option with `/librget config safechecker false`
