### ISSUE TITLE
there appears to be no version for 1.17 (1.17 version request)

### ISSUE THREAD

**Issue by yeetus-maximus** [gXLg/libr-getter#4]
could you compile a version for 1.17 please, thanks in advance or perhaps i could try compiling it for 1.17 myself

**Comment by gXLg** [comment]
1.17 seems to work with 1.16.5 version, as well as all other versions from 1.16.2 to 1.17.1, I may change description in soon future as well

**Comment by yeetus-maximus** [comment]
im not sure but 1.17 appears to crash once you start the process

**Comment by gXLg** [comment]
Alright, will make a branch for 1.17 as well

**Comment by gXLg** [comment]
Done in https://github.com/gXLg/libr-getter/releases/tag/v1.2.4
