### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by TwoPointInfinity** [gXLg/libr-getter#6]
would you update please? no longer works in 1.19.3

**Comment by gXLg** [comment]
Whoops, I forgot that 1.19.3 is not compatible with 1.19.2. I will update it as soon as possible

**Comment by gXLg** [comment]
(not ready yet, they changed a lot in such a small version, I have to figure out, and sorry for taking so long)

**Comment by TwoPointInfinity** [comment]
hay no worries. i did see they changed many variables in the 1.19.3 update and it honestly broke like almost every mod. I dont blame you for taking time.

**Comment by gXLg** [comment]
Hello! Thanks for waiting! The mod is updated in [v1.2.6](https://github.com/gXLg/libr-getter/releases/tag/v1.2.6)
