### ISSUE TITLE
Make a sound when it finds a book

### ISSUE THREAD

**Issue by Viruzaum** [gXLg/libr-getter#7]
Would be nice to have a sound to notify when the mod finds one of the selected books.

**Comment by gXLg** [comment]
Hello! Thank you, this is an interesting idea, didn't think about it. Will add this ASAP, and there are some more ideas in my head for the next update, so stay tuned!

**Comment by gXLg** [comment]
Added in [v1.2.7](https://github.com/gXLg/libr-getter/releases/tag/v1.2.7)
