### ISSUE TITLE
[ Suggestion ] Add max amount of emeralds for price

### ISSUE THREAD

**Issue by Godwhitelight** [gXLg/libr-getter#9]
simple add an arguemnt for emerald min amount for the trade. default will be without limit.

**Comment by gXLg** [comment]
Do you mean max amount?

**Comment by Godwhitelight** [comment]
yh (am so dumb lol)

**Comment by gXLg** [comment]
This is included in the newest update, now just need to port it to all supported versions and bring out a release

**Comment by gXLg** [comment]
Added in [v1.2.7](https://github.com/gXLg/libr-getter/releases/tag/v1.2.7)
